/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 01b9b25ce387e835292eb362e9bb3049)
interface __BaseEnv_Env {
	KV: KVNamespace;
	R2_ASSETS: R2Bucket;
	ASSETS: Fetcher;
	SITE_NAME: "HAJIMEコンサルティング株式会社";
	SITE_URL: "https://hajime-jp.co.jp";
	BREVO_SENDER_NAME: "HAJIMEコンサルティング株式会社";
	BREVO_SENDER_EMAIL: "notify@hajime-jp.co.jp";
	CONTACT_RECIPIENT_NAME: "HAJIMEコンサルティング株式会社";
	CONTACT_RECIPIENT_EMAIL: "info@hajime-jp.co.jp";
	CONTACT_REPLY_TO_NAME: "HAJIMEコンサルティング株式会社";
	CONTACT_REPLY_TO_EMAIL: "info@hajime-jp.co.jp";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_NAME" | "SITE_URL" | "BREVO_SENDER_NAME" | "BREVO_SENDER_EMAIL" | "CONTACT_RECIPIENT_NAME" | "CONTACT_RECIPIENT_EMAIL" | "CONTACT_REPLY_TO_NAME" | "CONTACT_REPLY_TO_EMAIL">> {}
}
